export interface StudentListProfileEnrollmentDto {
  "id": string
  "courseName": string
  "package": string
  "level": string
  "modality": string
  "academicPeriod": string
  "schedule": string
  "duration": string
  "monthlyFee": number
  "age": number
  "courseFee": number
  "installments": number
  "days": number
  "months": string
  "years": number
  "times": Date
  "documentType": string
  "idNumber": string
  "placeOfIssue": string
  "expirationDate": string
  "fullName": string
  "dateOfBirth": string
  "gender": string
  "maritalStatus": string
  "nationality": string
  "placeOfBirth": string
  "residentialAddress": string
  "firstPhoneNumber": string
  "secondPhoneNumber": string
  "emailAddress": string
  "additionalNotes": string
  "guardFullName": string
  "guardRelationship": string
  "guardResidentialAddress": string
  "guardFirstPhoneNumber": string
  "guardSecondPhoneNumber": string
  "guardEmailAddress": string
}
